development:
  adapter: async
  url: redis://redistogo:2896b6df72eea6887bc39b157457afef@barreleye.redistogo.com:9833/

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
