# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3a361f260d3af45095fe5aea68ea2e9b427a6e67ed2c00ee8ea078b2e523a6b401670635028f6889a3acf7197764e3008fc7d7331969c7b2a8227440ff3737a

test:
  secret_key_base: 8849946b7fc4ff4a754faf7d236c5216d911cc171747e3060b9f8f42ef6a27e5a35f23abdd6e83710cd1ff79cfb2d5053ba2ddd68bb8e3a15f3441726d823279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
