User.create!([
  {username: "libbie.fahey", password_digest: "$2a$10$HLmVndyX2GuevpJ/mWt1wOGsqQttHNt.kcdMqQ8YEiguRSAlNB7iK", session_token: "HcYAsd8VoT7oIROPKg0MXg", image: "https://robohash.org/utiurepraesentium.png?size=300x300&set=set1"},
  {username: "emelia", password_digest: "$2a$10$Sr21vT07Mn4JDZ1INeRpwuAhEQoaQHmRjpFDdxeMR3ix46HRXCCG.", session_token: "4zRj4b9EBHwOM3PfwU5eFA", image: "https://robohash.org/adsitimpedit.png?size=300x300&set=set1"},
  {username: "ezekiel", password_digest: "$2a$10$24DpJwqzDnqNDqe4yLOaAOFYjzvUxlM6GSbyYbJklSdT.S2Q1FnyC", session_token: "TT7a4vIB3nktxjN0rGs7jg", image: "https://robohash.org/officiissintsuscipit.png?size=300x300&set=set1"},
  {username: "dell", password_digest: "$2a$10$BT4/GsmDm7Xa/gMRcD6/DeeO9B41EXPKTSWfEpI69Dh.naJyuydiW", session_token: "95nbJJR48n-Lnb3udHBUTQ", image: "https://robohash.org/utrepudiandaevoluptas.png?size=300x300&set=set1"},
  {username: "sadye_reichert", password_digest: "$2a$10$ZscbVJKQ8ChN5WQZ6GOJRuUpaT92xjKWDVMWNZCu6GuZlc4rPT3Ta", session_token: "KvufTc0AswkBmSRiCQTl3A", image: "https://robohash.org/iustodoloremqueharum.png?size=300x300&set=set1"},
  {username: "tristin.schamberger", password_digest: "$2a$10$CtaY6C5NpmmKX9MSJ4K6s.i/iWXMsRRWbsXdJzs4L7KLW6zxsL8sq", session_token: "0ZfAC4o9N_nO-QgAf00qhQ", image: "https://robohash.org/providentmolestiaeofficiis.png?size=300x300&set=set1"},
  {username: "magdalen_watsica", password_digest: "$2a$10$zCXMZqmsjv0luM5BzhowFuomi7BgjPf6OD2RmicXgpMJxb51JifxS", session_token: "yQknBG_68lNsW_1aTg_7cw", image: "https://robohash.org/eosdoloribusvelit.png?size=300x300&set=set1"},
  {username: "kayleigh", password_digest: "$2a$10$VXvWee93JqNK.uOStMx6UOkYS1afbAqQsOB.1IZKXZzLZEwHZqQqi", session_token: "QddhiPDUiiBgLuQ6mOdERw", image: "https://robohash.org/facilisanimirecusandae.png?size=300x300&set=set1"},
  {username: "lia_tremblay", password_digest: "$2a$10$R.iw7hPJgu7JeR07cXXDouIpcDAqsWMoECZrdQJftvTllpZQGG086", session_token: "gYXN8Xtzond97VS5Db8zfA", image: "https://robohash.org/providentdoloreset.png?size=300x300&set=set1"},
  {username: "arianna.powlowski", password_digest: "$2a$10$OI62AUm8WAjtkKo2Z.uyw.ZR/2CTfQwEmnJ8apvDfUf4pzPZgnta6", session_token: "1jyt7cahqY1ZUhLw_n6kvg", image: "https://robohash.org/faceredolorat.png?size=300x300&set=set1"},
  {username: "kavon_strosin", password_digest: "$2a$10$gd2/E8f6RQwsn0ngU2N3q.2aFUuVodU2mz.VDpdQnPilO4KO88hN6", session_token: "NmEvl0ZY5zFHnqb1B3dByA", image: "https://robohash.org/etomnispossimus.png?size=300x300&set=set1"},
  {username: "madison_prosacco", password_digest: "$2a$10$z02NNP.a8emxVmRhZk94MOjLBQDgg5ia.yQymCxchFgCouFomQVQK", session_token: "gWgUkVFIcgLOch8HOGrVZg", image: "https://robohash.org/aperiamdistinctiosed.png?size=300x300&set=set1"},
  {username: "kristopher.kuvalis", password_digest: "$2a$10$WlP7402SYB30JgHVGNQszerR/1EI6kkDZPaADWVjpyf//YrO.6Yam", session_token: "ABO9trsnjf2Gsh9FvNhYCw", image: "https://robohash.org/praesentiumvoluptasadipisci.png?size=300x300&set=set1"},
  {username: "una_mertz", password_digest: "$2a$10$e3jzhZlCXMPfHK3rux.sKe4nx32ki6DY2YmtxDqcx.ufvSyc47dNS", session_token: "o9qRhL2yQe3fLHkMtS8l6g", image: "https://robohash.org/doloremeumvelit.png?size=300x300&set=set1"},
  {username: "naomie", password_digest: "$2a$10$kN0.E3Zb1ua8y8Gxmb2QUuDaKPxXxvgpnErUhV7fys6WvLGh5shKK", session_token: "PEFuy_vvk8YJzW9Bl12c4w", image: "https://robohash.org/officiaminusvel.png?size=300x300&set=set1"},
  {username: "kris.schinner", password_digest: "$2a$10$lFl0Pbbtl9JvMiqH0mtaiu2Jtd3P9XuDK1qctXoINz88n36RUCZeq", session_token: "HYu5GpqX-9PTLXb43Ch0Bg", image: "https://robohash.org/sedipsumnumquam.png?size=300x300&set=set1"},
  {username: "lorena.hermiston", password_digest: "$2a$10$VkTyWEOoEMQ0nMuqVLWXGeWOvxZSYuRurm8Fr2KMjf7IZ/QPCFnRa", session_token: "97VDcIgeodB1LNS4xB18-w", image: "https://robohash.org/ipsamrepudiandaeexcepturi.png?size=300x300&set=set1"},
  {username: "verna", password_digest: "$2a$10$rMbdPDipIQUPDRLqmtLNb.zRDki/sPXYyXRcMvJjyVhtlm3W80Gri", session_token: "NmxgqcdO9B55EXEMmWqb_g", image: "https://robohash.org/odioidminus.png?size=300x300&set=set1"},
  {username: "jasen", password_digest: "$2a$10$XEsBYiASeKVdaTKaeutAZOv4u6y9uNk1jcLz.d7cSDGMf79s5eDkO", session_token: "qn8ARuAaV6HoIP2mLUTzWg", image: "https://robohash.org/totamametquasi.png?size=300x300&set=set1"},
  {username: "guadalupe", password_digest: "$2a$10$RgQyFwISYURBHIMsIECwuunrggGC0Ru84q9ahN443a/Id.hqsIe8K", session_token: "CKN9OswdREdMXZ47VIseVw", image: "https://robohash.org/iustoplaceatin.png?size=300x300&set=set1"},
  {username: "julius_hansen", password_digest: "$2a$10$GSkUlJDQ1hVqxpNHHhwIDeJvjFldR5W0wwKLPfHVF7kVBVJ65RYVO", session_token: "O9xFU4xV2E47zqTMwKuCIg", image: "https://robohash.org/quispariaturculpa.png?size=300x300&set=set1"},
  {username: "alyson", password_digest: "$2a$10$ypBWXJsJ..qN/.pFXSYaC.nde1Vmf0zzOW0DL8PCUlJqVc/IAxicm", session_token: "1v3aMngHYBNG_05TzcdTtg", image: "https://robohash.org/repellatlaudantiumeos.png?size=300x300&set=set1"},
  {username: "frederik", password_digest: "$2a$10$5dYK1.QZl1hbFCAQK3rTJutl/YpWYpLX4YcGF7CpyqpDYUUIbX8.y", session_token: "fvYXv2QIdg2-V2U0BxuDUg", image: "https://robohash.org/fugamagnirepudiandae.png?size=300x300&set=set1"},
  {username: "autumn", password_digest: "$2a$10$ipN2SKGjO4TUWJC2GFiY6OqBqRXjB30IwtflTsCjvosYYJ/lS3Bl.", session_token: "05Ntc1BCxItHzUAH7UY4HQ", image: "https://robohash.org/fugitexplicabovoluptas.png?size=300x300&set=set1"},
  {username: "keanu.abbott", password_digest: "$2a$10$5IQ/GV.XS3JJUcLFjmNVPuj.A/de6GcuiKwRZv.TMAzZZin192iq6", session_token: "Xg74I5ciWafDMKYowtCkSQ", image: "https://robohash.org/nonillosapiente.png?size=300x300&set=set1"},
  {username: "santiago.hoeger", password_digest: "$2a$10$Q25XyQekb4obL7hptQi79en1YELF7a4zpudyECXu4pUGC/Fpl..e2", session_token: "YzqD4_PbOpvUQEt5Qx5SJQ", image: "https://robohash.org/sitexercitationemeum.png?size=300x300&set=set1"},
  {username: "noemie", password_digest: "$2a$10$buBFmOI/.VQ.4E6/wfB4NOQndi21Vf4D7ooqpM8CJqnzrxtlL0O2y", session_token: "TdSSHa9fdaEQA-QdEQ0IpA", image: "https://robohash.org/liberoremquas.png?size=300x300&set=set1"},
  {username: "odie", password_digest: "$2a$10$gifZVjlnquBkzUi3hSPnlOeZrLX7UYGfvhhpAl3/ewiIJZMek1quG", session_token: "OUds0LnZvaxpjsoz2pTSFw", image: "https://robohash.org/enimrepellatdoloremque.png?size=300x300&set=set1"},
  {username: "garry", password_digest: "$2a$10$z.NU9DjgCOzfhaPduydGNOFRYMzpICQf7b9NUg0g8RURGyjn0UHPm", session_token: "o5YYlIFxpH7Cr3zzDBHqvw", image: "https://robohash.org/istevelitquia.png?size=300x300&set=set1"},
  {username: "harmon", password_digest: "$2a$10$BlE4qne2d3DsiVJtT/WsfOlYxLtgwlH9GfOhiFYzDCDQYqa/9ytaK", session_token: "GZtG4amZ3LOxNnzAxlw4OQ", image: "https://robohash.org/suntpariaturquidem.png?size=300x300&set=set1"},
  {username: "jettie", password_digest: "$2a$10$.4LlpDFdZjYEieEKJkCjSO8uPKwI.rIH1O6v8RyGY06QIEMK879I.", session_token: "CIEBQkYTena3cvebikh2mQ", image: "https://robohash.org/corporisvoluptasvoluptatem.png?size=300x300&set=set1"},
  {username: "chet", password_digest: "$2a$10$DDwc2G092O5nsYhsCpkT3O3vBg0.1bX0DjEgcITlO6SY47ss4g2uq", session_token: "mkbh-VyxyV5vMXsnOxQkpA", image: "https://robohash.org/quoestest.png?size=300x300&set=set1"},
  {username: "nathen.mills", password_digest: "$2a$10$Qz6hbR.HVePtBgONNzeL8uS9WdXlGHMUiDx.u08b48.zEBFr4zfxy", session_token: "13X846LfqkSpBsDY9vu26g", image: "https://robohash.org/temporavitaeomnis.png?size=300x300&set=set1"},
  {username: "heather", password_digest: "$2a$10$G8tMlYuBOrAlNCY6m0QsveJ9rd14mAeY7BTrTUtBS5BOsjpP2dku2", session_token: "PlUh2SSO3-x8TEiX-wogRw", image: "https://robohash.org/minimaquisvoluptatem.png?size=300x300&set=set1"},
  {username: "abe", password_digest: "$2a$10$.H//7l/Dws0tThhMfaROL.4l8MW7DHpYpJxlgtqsoerSVrOWfcPHe", session_token: "oQUfx6xSJ9aBOLa4_RwN7A", image: "https://robohash.org/laudantiumtemporaa.png?size=300x300&set=set1"},
  {username: "caroline", password_digest: "$2a$10$MqiUir8yTTbS1c4lg0KeuO5WJJ8zXFIGePtNWzrhkZJWTTCDw/RnO", session_token: "AYCAmX2zWp_HwY4hDBg-xA", image: "https://robohash.org/doloremcupiditatevoluptates.png?size=300x300&set=set1"},
  {username: "amara_dooley", password_digest: "$2a$10$0KfGwhGcx70WAtjxsWxdZOYUBCol6U9eLcEO5HJCE8lEN6z473yzK", session_token: "1nhkicA4MgnUvUNC28fjfA", image: "https://robohash.org/quiaetnihil.png?size=300x300&set=set1"},
  {username: "sharon", password_digest: "$2a$10$ZNWW3/QJ3ZyTYVEWqI3tf.HL9Frf69Ii1M319.ImV.m9LNVNeIXPa", session_token: "kd6FhawrOw6onzvMx30vEw", image: "https://robohash.org/estetducimus.png?size=300x300&set=set1"},
  {username: "marc.mayert", password_digest: "$2a$10$JwuuzJuOgLa9kOLp/Q82j./S7OKcson34qLaK4UuRNM0xgIyLMh2W", session_token: "8IzgbYp_ai5Qm3zJMnsyLQ", image: "https://robohash.org/namnostrumeaque.png?size=300x300&set=set1"},
  {username: "lilly_johnston", password_digest: "$2a$10$J2Ino.2zF4v9c37mtoIgV.OQXaYznnbylPTcQ4WAF1fAMoiXKBr62", session_token: "shJdvhgnpDXQ5jSdT_AhZg", image: "https://robohash.org/quideserunteos.png?size=300x300&set=set1"},
  {username: "omer", password_digest: "$2a$10$.GGOVVXEQhXj0uy49u56ne4vu1ju8le.aMXsu6Km6JfdYXv6jo2ce", session_token: "JEp1nsVLDuafDaHnugnviw", image: "https://robohash.org/undererumearum.png?size=300x300&set=set1"},
  {username: "jaclyn", password_digest: "$2a$10$c2UExPfD0bGYrlV.VM.SAuykaWpamcprSsPGgWL5Qc.VwoR2JBhyu", session_token: "PyYl6BzEdeAWBBQSvM1xlA", image: "https://robohash.org/temporecorporisquis.png?size=300x300&set=set1"},
  {username: "dayne_ohara", password_digest: "$2a$10$/HHSAIO5HcbT2fDYSNjbSumZ1lgMzarqdnZxqPrzWrjS9c3iG9fQK", session_token: "gj1HaUtGCUFtdh0reJk70Q", image: "https://robohash.org/velitquisquo.png?size=300x300&set=set1"},
  {username: "adalberto_larson", password_digest: "$2a$10$eRv//VUaOh95/iDDx9xYp.5yhBOXmNw6q9yJhnFe4L7dqThuEGjqW", session_token: "dHAZ2itX8iHlZu7KQ64yDQ", image: "https://robohash.org/quiperspiciatisnumquam.png?size=300x300&set=set1"},
  {username: "garret_johnson", password_digest: "$2a$10$/9x5bJvleT85awcuz0Cp4.336AX3FW1nLZwr9n/z10GIvj9fXk5Mu", session_token: "ToPqZy0SGtFSVRS_-CScrg", image: "https://robohash.org/quiaquamquis.png?size=300x300&set=set1"},
  {username: "electa_harris", password_digest: "$2a$10$VOcH/lBRvTSCIxolzsCyaeqYqVw5S0Wr9Qh96AvJwEGgbDQihmzW6", session_token: "ofKnMosrk2l7AFn78wVm4g", image: "https://robohash.org/temporibusdolorealiquam.png?size=300x300&set=set1"},
  {username: "victoria", password_digest: "$2a$10$scG9prF2T.6htxQUfQ/jUeRcyky0A5b.mT5SQPOpz0kuGiulLBFja", session_token: "1Y5CuS63qspiOl5y-jwrFA", image: "https://robohash.org/quopariaturiste.png?size=300x300&set=set1"},
  {username: "randall_schmeler", password_digest: "$2a$10$fiX2wXaalJPcV7USPxUHOOw3Xmcpkige0sL5X5IuESAMAMaXA95gW", session_token: "RrI9amMrmy8Ffmyd-vuypQ", image: "https://robohash.org/minusnihilvelit.png?size=300x300&set=set1"},
  {username: "tomas", password_digest: "$2a$10$sQSmtVjtaavm/666L2rt1.5T3ILTQFpghigfP4rA0YEfEnjj/wiGS", session_token: "h1_RSM0qPpn67NvUD78w3A", image: "https://robohash.org/numquamaliquidinventore.png?size=300x300&set=set1"},
  {username: "mckenzie_hand", password_digest: "$2a$10$G17XlUm.3K4MxuFL.KywP.E.VKrlmKsUc9fJ47WuenEkk8vsRjhLS", session_token: "2odJUGiPs7yv-1ZVlhdfSA", image: "https://robohash.org/undedeseruntdolorem.png?size=300x300&set=set1"},
  {username: "ryley_sill", password_digest: "$2a$10$2CHAiVIN6.Uc058xCVTuUOYtVE3sNeWGXcTQtF1grG/kXBjESb2/2", session_token: "g21GwUybelqTHrBlWT8fMg", image: "http://res.cloudinary.com/dwqeotsx5/image/upload/v1490378548/Ryley_Sill_omsfin.png"},
  {username: "earl.dickinson", password_digest: "$2a$10$RuBjPFPaKoaei7wjwYSZjOF6MwadIOg4wfdrq6ItIl7BYd2wRf2La", session_token: "merVI5N1GPTqN6myrM_DtQ", image: "https://robohash.org/velitcumqueest.png?size=300x300&set=set1"},
  {username: "everette", password_digest: "$2a$10$ncXSZnD08l3dd/UOOCBWxOyeCV6iRI4TkBFbzhz9BDUSEFAXF2UgG", session_token: "LrqoXsrghGMbyzLkc5_kKA", image: "https://robohash.org/doloremquisquamquis.png?size=300x300&set=set1"}
  ])

Channel.create!([
  {title: "general", kind: "channel"},
  {title: "music", kind: "channel"},
  {title: "outdoors", kind: "channel"},
  {title: "food", kind: "channel"},
  {title: "ryley_sill", kind: "direct"},
  {title: "libbie.fahey", kind: "direct"},
  {title: "emelia", kind: "direct"},
  {title: "ezekiel", kind: "direct"},
  {title: "dell", kind: "direct"},
  {title: "ryley_sill", kind: "direct"},
  {title: "libbie.fahey", kind: "direct"},
  {title: "emelia", kind: "direct"},
  {title: "ezekiel", kind: "direct"},
  {title: "dell", kind: "direct"}
])
Membership.create!([
  {channel_id: 1, user_id: 51},
  {channel_id: 2, user_id: 51},
  {channel_id: 3, user_id: 51},
  {channel_id: 4, user_id: 51},
  {channel_id: 1, user_id: 41},
  {channel_id: 1, user_id: 38},
  {channel_id: 1, user_id: 11},
  {channel_id: 1, user_id: 47},
  {channel_id: 1, user_id: 45},
  {channel_id: 1, user_id: 13},
  {channel_id: 1, user_id: 43},
  {channel_id: 1, user_id: 3},
  {channel_id: 1, user_id: 2},
  {channel_id: 1, user_id: 23},
  {channel_id: 1, user_id: 6},
  {channel_id: 1, user_id: 8},
  {channel_id: 1, user_id: 19},
  {channel_id: 1, user_id: 28},
  {channel_id: 1, user_id: 36},
  {channel_id: 1, user_id: 7},
  {channel_id: 1, user_id: 18},
  {channel_id: 1, user_id: 34},
  {channel_id: 1, user_id: 25},
  {channel_id: 1, user_id: 46},
  {channel_id: 1, user_id: 16},
  {channel_id: 1, user_id: 20},
  {channel_id: 1, user_id: 9},
  {channel_id: 1, user_id: 4},
  {channel_id: 2, user_id: 5},
  {channel_id: 2, user_id: 11},
  {channel_id: 2, user_id: 4},
  {channel_id: 2, user_id: 25},
  {channel_id: 2, user_id: 10},
  {channel_id: 2, user_id: 22},
  {channel_id: 2, user_id: 44},
  {channel_id: 2, user_id: 19},
  {channel_id: 2, user_id: 40},
  {channel_id: 2, user_id: 39},
  {channel_id: 2, user_id: 34},
  {channel_id: 2, user_id: 18},
  {channel_id: 2, user_id: 3},
  {channel_id: 2, user_id: 8},
  {channel_id: 2, user_id: 33},
  {channel_id: 2, user_id: 35},
  {channel_id: 2, user_id: 47},
  {channel_id: 2, user_id: 17},
  {channel_id: 2, user_id: 49},
  {channel_id: 2, user_id: 36},
  {channel_id: 2, user_id: 21},
  {channel_id: 2, user_id: 14},
  {channel_id: 2, user_id: 9},
  {channel_id: 2, user_id: 23},
  {channel_id: 2, user_id: 31},
  {channel_id: 2, user_id: 29},
  {channel_id: 2, user_id: 24},
  {channel_id: 2, user_id: 48},
  {channel_id: 2, user_id: 28},
  {channel_id: 3, user_id: 32},
  {channel_id: 3, user_id: 8},
  {channel_id: 3, user_id: 27},
  {channel_id: 3, user_id: 18},
  {channel_id: 3, user_id: 45},
  {channel_id: 3, user_id: 41},
  {channel_id: 3, user_id: 36},
  {channel_id: 3, user_id: 16},
  {channel_id: 3, user_id: 1},
  {channel_id: 3, user_id: 37},
  {channel_id: 3, user_id: 39},
  {channel_id: 3, user_id: 34},
  {channel_id: 3, user_id: 17},
  {channel_id: 3, user_id: 3},
  {channel_id: 3, user_id: 10},
  {channel_id: 3, user_id: 40},
  {channel_id: 3, user_id: 2},
  {channel_id: 3, user_id: 14},
  {channel_id: 3, user_id: 13},
  {channel_id: 3, user_id: 23},
  {channel_id: 3, user_id: 38},
  {channel_id: 3, user_id: 44},
  {channel_id: 3, user_id: 9},
  {channel_id: 4, user_id: 21},
  {channel_id: 4, user_id: 48},
  {channel_id: 4, user_id: 23},
  {channel_id: 4, user_id: 41},
  {channel_id: 4, user_id: 47},
  {channel_id: 4, user_id: 7},
  {channel_id: 4, user_id: 20},
  {channel_id: 4, user_id: 14},
  {channel_id: 4, user_id: 50},
  {channel_id: 4, user_id: 40},
  {channel_id: 4, user_id: 24},
  {channel_id: 4, user_id: 2},
  {channel_id: 4, user_id: 10},
  {channel_id: 4, user_id: 33},
  {channel_id: 4, user_id: 45},
  {channel_id: 4, user_id: 8},
  {channel_id: 4, user_id: 19},
  {channel_id: 4, user_id: 16},
  {channel_id: 4, user_id: 9},
  {channel_id: 4, user_id: 42},
  {channel_id: 4, user_id: 22},
  {channel_id: 4, user_id: 27},
  {channel_id: 4, user_id: 32},
  {channel_id: 4, user_id: 44},
  {channel_id: 4, user_id: 11},
  {channel_id: 5, user_id: 52},
  {channel_id: 1, user_id: 52},
  {channel_id: 6, user_id: 52},
  {channel_id: 6, user_id: 1},
  {channel_id: 2, user_id: 52},
  {channel_id: 7, user_id: 52},
  {channel_id: 7, user_id: 2},
  {channel_id: 3, user_id: 52},
  {channel_id: 8, user_id: 52},
  {channel_id: 8, user_id: 3},
  {channel_id: 4, user_id: 52},
  {channel_id: 9, user_id: 52},
  {channel_id: 9, user_id: 4},
  {channel_id: 10, user_id: 53},
  {channel_id: 1, user_id: 53},
  {channel_id: 11, user_id: 53},
  {channel_id: 11, user_id: 1},
  {channel_id: 2, user_id: 53},
  {channel_id: 12, user_id: 53},
  {channel_id: 12, user_id: 2},
  {channel_id: 3, user_id: 53},
  {channel_id: 13, user_id: 53},
  {channel_id: 13, user_id: 3},
  {channel_id: 4, user_id: 53},
  {channel_id: 14, user_id: 53},
  {channel_id: 14, user_id: 4}
])
Message.create!([
  {body: "Meh church-key vegan tofu wes anderson.", author_id: 10, channel_id: 1, gif_url: nil},
  {body: "Fanny pack pug biodiesel selvage chia kombucha whatever narwhal actually.", author_id: 13, channel_id: 2, gif_url: nil},
  {body: "Chambray vhs synth jean shorts brunch salvia kogi marfa.", author_id: 17, channel_id: 3, gif_url: nil},
  {body: "Small batch squid food truck kale chips tousled ramps pour-over.", author_id: 15, channel_id: 4, gif_url: nil},
  {body: "Offal vice flannel twee banh mi pinterest post-ironic narwhal 8-bit.", author_id: 10, channel_id: 1, gif_url: nil},
  {body: "Seitan health lumbersexual craft beer stumptown.", author_id: 14, channel_id: 2, gif_url: nil},
  {body: "Taxidermy synth brooklyn actually art party pitchfork loko flannel pabst.", author_id: 10, channel_id: 3, gif_url: nil},
  {body: "Post-ironic pop-up cornhole polaroid cold-pressed before they sold out.", author_id: 19, channel_id: 4, gif_url: nil},
  {body: "Echo hella distillery chia pickled art party lo-fi.", author_id: 15, channel_id: 1, gif_url: nil},
  {body: "Blue bottle wolf whatever tousled brunch tumblr actually.", author_id: 14, channel_id: 2, gif_url: nil},
  {body: "Schlitz cray shoreditch salvia ramps mumblecore.", author_id: 2, channel_id: 3, gif_url: nil},
  {body: "Plaid health skateboard tote bag.", author_id: 9, channel_id: 4, gif_url: nil},
  {body: "Cliche migas austin wolf.", author_id: 7, channel_id: 1, gif_url: nil},
  {body: "Keffiyeh neutra ugh semiotics meh squid occupy art party pitchfork.", author_id: 3, channel_id: 2, gif_url: nil},
  {body: "Vinyl direct trade vhs hashtag cardigan literally listicle poutine.", author_id: 5, channel_id: 3, gif_url: nil},
  {body: "Next level roof health locavore ramps chillwave gluten-free pug paleo.", author_id: 18, channel_id: 4, gif_url: nil},
  {body: "Tousled actually street goth tacos skateboard.", author_id: 11, channel_id: 1, gif_url: nil},
  {body: "Salvia leggings aesthetic bushwick roof forage cornhole tofu.", author_id: 6, channel_id: 2, gif_url: nil},
  {body: "Kitsch mlkshk flannel salvia pop-up.", author_id: 16, channel_id: 3, gif_url: nil},
  {body: "Pabst pbr&b godard franzen neutra ethical meh selvage beard.", author_id: 8, channel_id: 4, gif_url: nil},
  {body: "Literally park marfa austin vhs venmo.", author_id: 14, channel_id: 1, gif_url: nil},
  {body: "Street pabst roof ethical.", author_id: 14, channel_id: 2, gif_url: nil},
  {body: "Vegan listicle vhs retro try-hard next level cronut small batch farm-to-table.", author_id: 10, channel_id: 3, gif_url: nil},
  {body: "Keffiyeh chia ennui raw denim.", author_id: 1, channel_id: 4, gif_url: nil},
  {body: "Kombucha tattooed flexitarian celiac yr venmo.", author_id: 1, channel_id: 1, gif_url: nil},
  {body: "Typewriter occupy tousled raw denim meh.", author_id: 19, channel_id: 2, gif_url: nil},
  {body: "Tumblr chambray asymmetrical salvia viral biodiesel kale chips health normcore.", author_id: 14, channel_id: 3, gif_url: nil},
  {body: "Kitsch listicle helvetica fashion axe shabby chic heirloom.", author_id: 2, channel_id: 4, gif_url: nil},
  {body: "Butcher schlitz lumbersexual sriracha.", author_id: 8, channel_id: 1, gif_url: nil},
  {body: "Forage synth pickled jean shorts pour-over blue bottle.", author_id: 11, channel_id: 2, gif_url: nil},
  {body: "Deep v wes anderson xoxo cardigan next level.", author_id: 11, channel_id: 3, gif_url: nil},
  {body: "Mumblecore kogi vice plaid carry marfa venmo twee farm-to-table.", author_id: 8, channel_id: 4, gif_url: nil},
  {body: "Chia pug letterpress selvage craft beer retro.", author_id: 10, channel_id: 1, gif_url: nil},
  {body: "Loko tumblr put a bird on it pitchfork irony.", author_id: 14, channel_id: 2, gif_url: nil},
  {body: "Deep v authentic pitchfork letterpress lomo flannel.", author_id: 8, channel_id: 3, gif_url: nil},
  {body: "Knausgaard neutra austin occupy chicharrones letterpress authentic ennui.", author_id: 11, channel_id: 4, gif_url: nil},
  {body: "Crucifix cronut freegan kickstarter sriracha green juice gastropub cliche.", author_id: 12, channel_id: 1, gif_url: nil},
  {body: "Lomo put a bird on it cold-pressed before they sold out godard.", author_id: 10, channel_id: 2, gif_url: nil},
  {body: "Kinfolk hammock bushwick brunch paleo heirloom tofu.", author_id: 3, channel_id: 3, gif_url: nil},
  {body: "Sustainable selfies photo booth meggings.", author_id: 14, channel_id: 4, gif_url: nil},
  {body: "Viral actually sartorial forage brunch xoxo street.", author_id: 4, channel_id: 1, gif_url: nil},
  {body: "Humblebrag everyday dreamcatcher shoreditch.", author_id: 7, channel_id: 2, gif_url: nil},
  {body: "Kombucha organic 90's migas biodiesel pug actually heirloom fanny pack.", author_id: 11, channel_id: 3, gif_url: nil},
  {body: "Vice drinking goth vegan schlitz 8-bit tofu.", author_id: 8, channel_id: 4, gif_url: nil},
  {body: "Gastropub vhs pinterest goth diy meggings drinking yuccie.", author_id: 13, channel_id: 1, gif_url: nil},
  {body: "You probably haven't heard of them offal thundercats xoxo.", author_id: 8, channel_id: 2, gif_url: nil},
  {body: "Asymmetrical bitters cliche 90's cold-pressed.", author_id: 20, channel_id: 3, gif_url: nil},
  {body: "Seitan pour-over chartreuse carry lomo +1 hoodie.", author_id: 1, channel_id: 4, gif_url: nil},
  {body: "Post-ironic fingerstache chartreuse skateboard.", author_id: 15, channel_id: 1, gif_url: nil},
  {body: "Flexitarian vegan bicycle rights neutra.", author_id: 3, channel_id: 2, gif_url: nil},
  {body: "Locavore lumbersexual tofu hoodie truffaut venmo goth.", author_id: 17, channel_id: 3, gif_url: nil},
  {body: "Wayfarers you probably haven't heard of them bitters scenester marfa kinfolk next level cliche cray.", author_id: 5, channel_id: 4, gif_url: nil},
  {body: "Chambray lomo craft beer master bicycle rights diy.", author_id: 15, channel_id: 1, gif_url: nil},
  {body: "Chia vice fashion axe forage chicharrones tofu.", author_id: 18, channel_id: 2, gif_url: nil},
  {body: "Five dollar toast forage cray letterpress bicycle rights.", author_id: 1, channel_id: 3, gif_url: nil},
  {body: "Umami try-hard knausgaard yr bespoke pop-up.", author_id: 15, channel_id: 4, gif_url: nil},
  {body: "Pinterest church-key meditation small batch mumblecore forage viral.", author_id: 18, channel_id: 1, gif_url: nil},
  {body: "Offal bitters migas pitchfork ugh.", author_id: 4, channel_id: 2, gif_url: nil},
  {body: "+1 paleo wayfarers pork belly you probably haven't heard of them asymmetrical hashtag pour-over brooklyn.", author_id: 13, channel_id: 3, gif_url: nil},
  {body: "Flannel +1 viral godard blog.", author_id: 8, channel_id: 4, gif_url: nil},
  {body: "Hashtag viral roof hammock.", author_id: 8, channel_id: 1, gif_url: nil},
  {body: "Pabst selvage lumbersexual artisan helvetica semiotics ramps viral.", author_id: 20, channel_id: 2, gif_url: nil},
  {body: "Tattooed lomo brooklyn ennui 3 wolf moon retro green juice offal sartorial.", author_id: 11, channel_id: 3, gif_url: nil},
  {body: "Iphone flexitarian franzen cleanse humblebrag.", author_id: 2, channel_id: 4, gif_url: nil},
  {body: "Echo kickstarter waistcoat iphone gentrify biodiesel tofu williamsburg bitters.", author_id: 19, channel_id: 1, gif_url: nil},
  {body: "Dreamcatcher keytar brunch sustainable venmo pour-over.", author_id: 2, channel_id: 2, gif_url: nil},
  {body: "Schlitz hella hammock lumbersexual.", author_id: 9, channel_id: 3, gif_url: nil},
  {body: "Dreamcatcher tumblr scenester chia humblebrag.", author_id: 8, channel_id: 4, gif_url: nil},
  {body: "Literally pbr&b selfies microdosing master.", author_id: 8, channel_id: 1, gif_url: nil},
  {body: "Goth celiac twee etsy echo scenester pickled quinoa green juice.", author_id: 9, channel_id: 2, gif_url: nil},
  {body: "Loko disrupt literally knausgaard.", author_id: 5, channel_id: 3, gif_url: nil},
  {body: "Bespoke pug tousled biodiesel.", author_id: 7, channel_id: 4, gif_url: nil},
  {body: "Goth drinking listicle tacos tattooed cray migas intelligentsia blue bottle.", author_id: 15, channel_id: 1, gif_url: nil},
  {body: "Keytar godard sriracha lomo irony chambray ramps.", author_id: 13, channel_id: 2, gif_url: nil},
  {body: "Taxidermy franzen cardigan narwhal goth.", author_id: 17, channel_id: 3, gif_url: nil},
  {body: "Yuccie biodiesel pitchfork heirloom health banh mi.", author_id: 1, channel_id: 4, gif_url: nil},
  {body: "Offal health twee cronut.", author_id: 13, channel_id: 1, gif_url: nil},
  {body: "90's freegan cleanse single-origin coffee distillery green juice neutra truffaut.", author_id: 10, channel_id: 2, gif_url: nil},
  {body: "Shabby chic freegan intelligentsia neutra.", author_id: 4, channel_id: 3, gif_url: nil},
  {body: "Goth selvage twee messenger bag.", author_id: 2, channel_id: 4, gif_url: nil},
  {body: "Shabby chic ethical distillery aesthetic twee health lo-fi hashtag.", author_id: 18, channel_id: 1, gif_url: nil},
  {body: "Iphone trust fund loko messenger bag williamsburg artisan retro next level carry.", author_id: 13, channel_id: 2, gif_url: nil},
  {body: "Pour-over yolo pabst chicharrones kinfolk godard.", author_id: 11, channel_id: 3, gif_url: nil},
  {body: "Blog fixie tacos iphone biodiesel cardigan next level bitters raw denim.", author_id: 15, channel_id: 4, gif_url: nil},
  {body: "Pinterest pork belly fanny pack polaroid vegan brunch.", author_id: 17, channel_id: 1, gif_url: nil},
  {body: "Salvia echo knausgaard lomo.", author_id: 12, channel_id: 2, gif_url: nil},
  {body: "Mumblecore pbr&b leggings vinegar artisan master selvage street.", author_id: 14, channel_id: 3, gif_url: nil},
  {body: "Twee readymade church-key craft beer.", author_id: 7, channel_id: 4, gif_url: nil},
  {body: "Readymade messenger bag aesthetic chicharrones butcher tattooed keffiyeh.", author_id: 17, channel_id: 1, gif_url: nil},
  {body: "Brooklyn meditation direct trade yuccie you probably haven't heard of them lo-fi.", author_id: 3, channel_id: 2, gif_url: nil},
  {body: "Cold-pressed waistcoat aesthetic small batch salvia viral banjo seitan cred.", author_id: 1, channel_id: 3, gif_url: nil},
  {body: "Normcore wes anderson plaid tacos small batch pabst direct trade butcher.", author_id: 16, channel_id: 4, gif_url: nil},
  {body: "Street carry fixie green juice hella banjo.", author_id: 1, channel_id: 1, gif_url: nil},
  {body: "Offal street pop-up helvetica.", author_id: 12, channel_id: 2, gif_url: nil},
  {body: "Venmo diy pinterest iphone 8-bit vegan.", author_id: 9, channel_id: 3, gif_url: nil},
  {body: "Portland pug marfa vegan kinfolk lumbersexual selvage 90's.", author_id: 17, channel_id: 4, gif_url: nil},
  {body: "Vinyl swag organic artisan drinking kitsch next level keytar.", author_id: 19, channel_id: 1, gif_url: nil},
  {body: "Letterpress green juice pbr&b direct trade cornhole.", author_id: 10, channel_id: 2, gif_url: nil},
  {body: "Iphone intelligentsia retro meggings.", author_id: 15, channel_id: 3, gif_url: nil},
  {body: "3 wolf moon butcher flannel paleo pickled before they sold out direct trade intelligentsia everyday.", author_id: 14, channel_id: 4, gif_url: nil},
  {body: "Etsy organic you probably haven't heard of them next level neutra tilde marfa iphone.", author_id: 14, channel_id: 1, gif_url: nil},
  {body: "Chillwave banjo readymade yuccie pbr&b tacos waistcoat.", author_id: 7, channel_id: 2, gif_url: nil},
  {body: "Lo-fi drinking cray everyday squid messenger bag ennui.", author_id: 6, channel_id: 3, gif_url: nil},
  {body: "Tofu chicharrones pug vice echo knausgaard.", author_id: 2, channel_id: 4, gif_url: nil},
  {body: "Beard pour-over actually selvage fashion axe swag williamsburg marfa park.", author_id: 5, channel_id: 1, gif_url: nil},
  {body: "Carry farm-to-table selfies portland vinegar.", author_id: 19, channel_id: 2, gif_url: nil},
  {body: "Pinterest flannel mumblecore plaid twee vhs wolf.", author_id: 15, channel_id: 3, gif_url: nil},
  {body: "Drinking readymade put a bird on it carry art party street.", author_id: 17, channel_id: 4, gif_url: nil},
  {body: "Before they sold out mixtape hella narwhal diy selvage messenger bag tilde.", author_id: 16, channel_id: 1, gif_url: nil},
  {body: "Sartorial slow-carb mixtape kitsch wayfarers.", author_id: 20, channel_id: 2, gif_url: nil},
  {body: "Retro marfa trust fund park aesthetic chia neutra knausgaard.", author_id: 14, channel_id: 3, gif_url: nil},
  {body: "Direct trade xoxo mlkshk chambray tote bag.", author_id: 16, channel_id: 4, gif_url: nil},
  {body: "Hella stumptown quinoa sriracha xoxo.", author_id: 9, channel_id: 1, gif_url: nil},
  {body: "Drinking health irony occupy cronut asymmetrical.", author_id: 11, channel_id: 2, gif_url: nil},
  {body: "Kickstarter cred bespoke fingerstache.", author_id: 8, channel_id: 3, gif_url: nil},
  {body: "3 wolf moon waistcoat cred butcher.", author_id: 9, channel_id: 4, gif_url: nil},
  {body: "Raw denim chambray fanny pack banjo tote bag.", author_id: 14, channel_id: 1, gif_url: nil},
  {body: "Quinoa kinfolk listicle lumbersexual typewriter cardigan.", author_id: 8, channel_id: 2, gif_url: nil},
  {body: "Authentic scenester photo booth hashtag try-hard pabst yr.", author_id: 6, channel_id: 3, gif_url: nil},
  {body: "Kitsch echo synth pop-up sustainable yr pbr&b stumptown selvage.", author_id: 3, channel_id: 4, gif_url: nil},
  {body: "Shoreditch microdosing sustainable pitchfork farm-to-table leggings.", author_id: 3, channel_id: 1, gif_url: nil},
  {body: "Mumblecore chartreuse iphone kickstarter franzen retro portland.", author_id: 17, channel_id: 2, gif_url: nil},
  {body: "Blog etsy trust fund next level roof marfa.", author_id: 15, channel_id: 3, gif_url: nil},
  {body: "Farm-to-table irony meh hella sartorial crucifix.", author_id: 20, channel_id: 4, gif_url: nil},
  {body: "Fingerstache franzen ramps tousled butcher knausgaard.", author_id: 11, channel_id: 1, gif_url: nil},
  {body: "Synth keffiyeh xoxo cray asymmetrical.", author_id: 2, channel_id: 2, gif_url: nil},
  {body: "Biodiesel humblebrag thundercats flexitarian skateboard post-ironic marfa tilde.", author_id: 9, channel_id: 3, gif_url: nil},
  {body: "Flexitarian williamsburg sriracha dreamcatcher seitan diy lo-fi cleanse.", author_id: 13, channel_id: 4, gif_url: nil},
  {body: "Butcher blue bottle tacos organic cred mumblecore.", author_id: 14, channel_id: 1, gif_url: nil},
  {body: "Microdosing meh park locavore iphone vinegar austin.", author_id: 4, channel_id: 2, gif_url: nil},
  {body: "Paleo flexitarian chillwave whatever gentrify art party.", author_id: 13, channel_id: 3, gif_url: nil},
  {body: "Small batch trust fund roof food truck echo.", author_id: 11, channel_id: 4, gif_url: nil},
  {body: "Fixie distillery vhs direct trade carry.", author_id: 17, channel_id: 1, gif_url: nil},
  {body: "Selvage ugh helvetica tumblr locavore listicle brooklyn art party.", author_id: 7, channel_id: 2, gif_url: nil},
  {body: "Gluten-free letterpress art party selfies messenger bag +1 cold-pressed.", author_id: 2, channel_id: 3, gif_url: nil},
  {body: "Diy franzen vinegar typewriter thundercats sustainable hoodie green juice pop-up.", author_id: 12, channel_id: 4, gif_url: nil},
  {body: "Pug tousled 8-bit echo everyday.", author_id: 9, channel_id: 1, gif_url: nil},
  {body: "Polaroid meditation food truck godard.", author_id: 4, channel_id: 2, gif_url: nil},
  {body: "Normcore seitan wayfarers banh mi offal vinegar literally.", author_id: 2, channel_id: 3, gif_url: nil},
  {body: "Pabst cleanse slow-carb church-key vinegar master try-hard.", author_id: 3, channel_id: 4, gif_url: nil},
  {body: "Meditation master thundercats food truck pbr&b messenger bag flexitarian etsy.", author_id: 17, channel_id: 1, gif_url: nil},
  {body: "Locavore pbr&b flannel mixtape plaid hashtag kogi.", author_id: 14, channel_id: 2, gif_url: nil},
  {body: "Tote bag ethical franzen pitchfork.", author_id: 6, channel_id: 3, gif_url: nil},
  {body: "Echo pug truffaut deep v.", author_id: 4, channel_id: 4, gif_url: nil},
  {body: "Fashion axe slow-carb tacos umami.", author_id: 12, channel_id: 1, gif_url: nil},
  {body: "Meh lomo marfa roof green juice hashtag.", author_id: 2, channel_id: 2, gif_url: nil},
  {body: "Locavore stumptown hammock offal goth blue bottle food truck.", author_id: 10, channel_id: 3, gif_url: nil},
  {body: "Put a bird on it salvia yuccie thundercats lumbersexual occupy hoodie craft beer.", author_id: 4, channel_id: 4, gif_url: nil},
  {body: "Kinfolk offal microdosing blog chicharrones.", author_id: 13, channel_id: 1, gif_url: nil},
  {body: "Kale chips jean shorts pitchfork flexitarian street trust fund bitters cleanse bicycle rights.", author_id: 17, channel_id: 2, gif_url: nil},
  {body: "Brooklyn disrupt yr gluten-free leggings authentic cliche.", author_id: 12, channel_id: 3, gif_url: nil},
  {body: "Helvetica cold-pressed +1 portland listicle tofu loko.", author_id: 20, channel_id: 4, gif_url: nil},
  {body: "Dreamcatcher everyday portland tousled yolo listicle kickstarter williamsburg.", author_id: 20, channel_id: 1, gif_url: nil},
  {body: "Echo occupy 8-bit squid.", author_id: 14, channel_id: 2, gif_url: nil},
  {body: "Polaroid 90's mixtape you probably haven't heard of them cold-pressed brooklyn schlitz blue bottle.", author_id: 18, channel_id: 3, gif_url: nil},
  {body: "Street messenger bag shoreditch portland cliche authentic taxidermy ugh.", author_id: 20, channel_id: 4, gif_url: nil},
  {body: "Vice hoodie shoreditch bicycle rights chillwave quinoa salvia.", author_id: 2, channel_id: 1, gif_url: nil},
  {body: "Slow-carb heirloom drinking park portland.", author_id: 4, channel_id: 2, gif_url: nil},
  {body: "Gluten-free squid offal street xoxo loko slow-carb.", author_id: 8, channel_id: 3, gif_url: nil},
  {body: "Tacos roof chambray beard tattooed.", author_id: 2, channel_id: 4, gif_url: nil},
  {body: "Pickled tousled mixtape sartorial listicle you probably haven't heard of them bitters.", author_id: 15, channel_id: 1, gif_url: nil},
  {body: "Tattooed forage fashion axe retro mixtape knausgaard.", author_id: 4, channel_id: 2, gif_url: nil},
  {body: "Vhs poutine migas pop-up five dollar toast hella taxidermy neutra chambray.", author_id: 6, channel_id: 3, gif_url: nil},
  {body: "Sustainable gentrify single-origin coffee post-ironic synth small batch street dreamcatcher mustache.", author_id: 15, channel_id: 4, gif_url: nil},
  {body: "Narwhal keffiyeh vice leggings.", author_id: 9, channel_id: 1, gif_url: nil},
  {body: "Post-ironic occupy cleanse irony wolf pbr&b helvetica taxidermy.", author_id: 13, channel_id: 2, gif_url: nil},
  {body: "Readymade fixie whatever brunch ennui everyday art party godard vhs.", author_id: 16, channel_id: 3, gif_url: nil},
  {body: "Sartorial craft beer austin +1 irony viral.", author_id: 10, channel_id: 4, gif_url: nil},
  {body: "Plaid knausgaard pour-over cornhole.", author_id: 20, channel_id: 1, gif_url: nil},
  {body: "Drinking pickled lomo heirloom fixie kinfolk.", author_id: 16, channel_id: 2, gif_url: nil},
  {body: "Chambray normcore gastropub stumptown blog.", author_id: 13, channel_id: 3, gif_url: nil},
  {body: "Biodiesel master tacos selvage.", author_id: 6, channel_id: 4, gif_url: nil},
  {body: "Letterpress fanny pack kombucha helvetica five dollar toast mlkshk.", author_id: 18, channel_id: 1, gif_url: nil},
  {body: "Waistcoat slow-carb pabst yolo.", author_id: 20, channel_id: 2, gif_url: nil},
  {body: "Bespoke flannel sriracha keytar artisan goth tousled quinoa humblebrag.", author_id: 20, channel_id: 3, gif_url: nil},
  {body: "Green juice fashion axe helvetica kogi kale chips cardigan.", author_id: 16, channel_id: 4, gif_url: nil},
  {body: "Ugh kale chips disrupt mumblecore migas chillwave.", author_id: 8, channel_id: 1, gif_url: nil},
  {body: "Normcore small batch hashtag ennui thundercats bespoke truffaut.", author_id: 15, channel_id: 2, gif_url: nil},
  {body: "Heirloom cray ramps health literally sriracha you probably haven't heard of them messenger bag mumblecore.", author_id: 14, channel_id: 3, gif_url: nil},
  {body: "Leggings irony freegan narwhal vinyl fashion axe venmo mustache taxidermy.", author_id: 20, channel_id: 4, gif_url: nil},
  {body: "Organic hashtag pitchfork tote bag cray roof wayfarers.", author_id: 3, channel_id: 1, gif_url: nil},
  {body: "Stumptown truffaut meditation jean shorts.", author_id: 13, channel_id: 2, gif_url: nil},
  {body: "Hammock before they sold out offal mixtape pinterest.", author_id: 5, channel_id: 3, gif_url: nil},
  {body: "Offal letterpress sartorial gluten-free cliche drinking swag.", author_id: 20, channel_id: 4, gif_url: nil},
  {body: "Meditation chia church-key 8-bit tofu cliche.", author_id: 18, channel_id: 1, gif_url: nil},
  {body: "Shoreditch skateboard thundercats bitters brunch pabst trust fund.", author_id: 9, channel_id: 2, gif_url: nil},
  {body: "Marfa you probably haven't heard of them helvetica organic.", author_id: 18, channel_id: 3, gif_url: nil},
  {body: "Echo gastropub pitchfork bicycle rights roof listicle.", author_id: 5, channel_id: 4, gif_url: nil},
  {body: "Humblebrag next level chia before they sold out put a bird on it stumptown.", author_id: 16, channel_id: 1, gif_url: nil},
  {body: "Lo-fi squid carry craft beer fashion axe shoreditch kale chips fixie messenger bag.", author_id: 16, channel_id: 2, gif_url: nil},
  {body: "Yr truffaut scenester brunch.", author_id: 4, channel_id: 3, gif_url: nil},
  {body: "Distillery offal scenester hella single-origin coffee.", author_id: 3, channel_id: 4, gif_url: nil},
  {body: "Retro yr meggings typewriter.", author_id: 5, channel_id: 1, gif_url: nil},
  {body: "Fanny pack thundercats semiotics pabst.", author_id: 16, channel_id: 2, gif_url: nil},
  {body: "Umami health normcore helvetica deep v pickled kickstarter small batch.", author_id: 17, channel_id: 3, gif_url: nil},
  {body: "Direct trade readymade gluten-free wolf park.", author_id: 7, channel_id: 4, gif_url: nil},
  {body: "Kickstarter locavore banh mi brooklyn waistcoat.", author_id: 4, channel_id: 1, gif_url: nil},
  {body: "Try-hard aesthetic chartreuse butcher swag.", author_id: 9, channel_id: 2, gif_url: nil},
  {body: "Freegan yolo beard yuccie mumblecore chambray mixtape.", author_id: 12, channel_id: 3, gif_url: nil},
  {body: "Humblebrag whatever heirloom keffiyeh.", author_id: 19, channel_id: 4, gif_url: nil},
  {body: "Brunch hoodie street readymade cornhole flannel fanny pack.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Freegan intelligentsia pbr&b plaid jean shorts before they sold out austin food truck.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Organic jean shorts food truck godard.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Leggings letterpress flannel franzen keytar synth vhs kickstarter kitsch.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Quinoa biodiesel shabby chic selfies normcore blue bottle church-key cornhole selvage.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Yr kombucha knausgaard master +1 vinegar.", author_id: 52, channel_id: 6, gif_url: nil},
  {body: "Messenger bag offal green juice flexitarian forage deep v scenester trust fund.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Kickstarter yuccie gluten-free pitchfork locavore.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Pork belly authentic bespoke cred microdosing kogi poutine typewriter sustainable.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Kombucha small batch cray umami put a bird on it.", author_id: 52, channel_id: 6, gif_url: nil},
  {body: "Readymade keffiyeh next level neutra jean shorts.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Gentrify tousled next level iphone dreamcatcher.", author_id: 52, channel_id: 6, gif_url: nil},
  {body: "Celiac put a bird on it flannel wes anderson sriracha mumblecore art party.", author_id: 52, channel_id: 6, gif_url: nil},
  {body: "Neutra freegan farm-to-table bicycle rights organic pop-up.", author_id: 52, channel_id: 6, gif_url: nil},
  {body: "Heirloom master poutine meditation skateboard mustache irony.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Celiac messenger bag cornhole freegan.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Everyday pinterest roof farm-to-table locavore bicycle rights you probably haven't heard of them flannel.", author_id: 52, channel_id: 6, gif_url: nil},
  {body: "Chicharrones before they sold out messenger bag keytar shabby chic.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Cornhole fixie blue bottle direct trade sartorial green juice disrupt chambray cray.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Literally chambray beard intelligentsia tote bag ramps banjo cold-pressed gentrify.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Irony diy vinegar listicle roof hella etsy schlitz ennui.", author_id: 52, channel_id: 6, gif_url: nil},
  {body: "Art party iphone hammock semiotics irony.", author_id: 52, channel_id: 6, gif_url: nil},
  {body: "Helvetica put a bird on it chambray raw denim whatever.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Yuccie selvage drinking beard scenester typewriter single-origin coffee pop-up.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Portland scenester pour-over jean shorts keffiyeh meggings diy fashion axe beard.", author_id: 1, channel_id: 6, gif_url: nil},
  {body: "Narwhal mustache aesthetic asymmetrical.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Blue bottle truffaut street tofu.", author_id: 52, channel_id: 7, gif_url: nil},
  {body: "Waistcoat carry sriracha iphone.", author_id: 52, channel_id: 7, gif_url: nil},
  {body: "Pop-up fixie thundercats street hoodie shoreditch lo-fi.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Fashion axe etsy yr roof viral poutine selfies.", author_id: 52, channel_id: 7, gif_url: nil},
  {body: "Tofu intelligentsia portland pork belly schlitz farm-to-table.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Cronut try-hard tumblr hoodie forage vinegar migas selvage.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Fashion axe craft beer +1 paleo deep v humblebrag photo booth.", author_id: 52, channel_id: 7, gif_url: nil},
  {body: "Freegan trust fund hashtag poutine cred.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Flexitarian retro direct trade food truck.", author_id: 52, channel_id: 7, gif_url: nil},
  {body: "Bushwick leggings retro pop-up flannel beard gluten-free.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Master etsy goth bicycle rights.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Ramps occupy church-key tousled.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Migas ramps kinfolk irony truffaut kombucha butcher literally occupy.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Migas trust fund vhs before they sold out pbr&b taxidermy.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Vinyl squid meh cred bushwick slow-carb.", author_id: 52, channel_id: 7, gif_url: nil},
  {body: "Tofu williamsburg chia sustainable blog gentrify tattooed church-key fanny pack.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Beard biodiesel paleo food truck before they sold out tilde occupy tattooed.", author_id: 52, channel_id: 7, gif_url: nil},
  {body: "Xoxo meggings hella fashion axe banjo.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Letterpress put a bird on it keytar goth master kombucha migas.", author_id: 52, channel_id: 7, gif_url: nil},
  {body: "Umami you probably haven't heard of them neutra next level gluten-free meggings mumblecore kombucha.", author_id: 52, channel_id: 7, gif_url: nil},
  {body: "Thundercats bespoke occupy plaid.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Blue bottle irony portland humblebrag.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Vhs ethical +1 meh small batch.", author_id: 52, channel_id: 7, gif_url: nil},
  {body: "Pbr&b helvetica waistcoat kogi tacos umami.", author_id: 2, channel_id: 7, gif_url: nil},
  {body: "Sartorial cred messenger bag occupy ramps ethical cliche tumblr.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Pug knausgaard green juice ramps blue bottle forage shoreditch tumblr retro.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Occupy mumblecore cronut master hammock 8-bit.", author_id: 52, channel_id: 8, gif_url: nil},
  {body: "Cornhole dreamcatcher blue bottle heirloom ennui street normcore schlitz.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Selfies biodiesel polaroid shoreditch helvetica post-ironic aesthetic heirloom slow-carb.", author_id: 52, channel_id: 8, gif_url: nil},
  {body: "Raw denim yolo kinfolk pinterest forage.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Chicharrones put a bird on it diy 90's.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Literally typewriter chartreuse retro intelligentsia.", author_id: 52, channel_id: 8, gif_url: nil},
  {body: "Pinterest green juice ramps ethical.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Knausgaard schlitz small batch yuccie selfies.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Tilde polaroid forage tousled banh mi.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Ethical mixtape vinyl polaroid kale chips meggings whatever tattooed.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "3 wolf moon tote bag lumbersexual banjo brooklyn before they sold out iphone.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Pbr&b sartorial carry pitchfork irony schlitz.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Dreamcatcher letterpress tattooed vegan.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Vinyl wolf 3 wolf moon small batch sriracha bitters pork belly chillwave dreamcatcher.", author_id: 52, channel_id: 8, gif_url: nil},
  {body: "Franzen irony +1 tousled iphone photo booth cliche.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Pug hashtag brunch yolo ennui.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Pork belly chia tousled kickstarter master kombucha.", author_id: 52, channel_id: 8, gif_url: nil},
  {body: "Post-ironic jean shorts echo bitters raw denim park chartreuse vice.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Deep v marfa disrupt heirloom locavore artisan photo booth listicle.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Chia meditation etsy meggings gastropub mustache pitchfork retro chambray.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Flannel single-origin coffee hashtag artisan roof kinfolk chartreuse.", author_id: 3, channel_id: 8, gif_url: nil},
  {body: "Cold-pressed blue bottle vice direct trade ethical pabst.", author_id: 52, channel_id: 8, gif_url: nil},
  {body: "Cred dreamcatcher irony keytar.", author_id: 52, channel_id: 8, gif_url: nil},
  {body: "Viral bespoke tilde goth ennui 8-bit tattooed trust fund swag.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Diy cronut banjo loko williamsburg forage.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "Vinyl farm-to-table chartreuse vhs.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Deep v brunch tumblr synth pop-up mumblecore wayfarers vegan.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "Skateboard thundercats narwhal banh mi.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Chambray art party 90's try-hard kale chips disrupt loko.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "Aesthetic food truck gentrify beard.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "Locavore street before they sold out readymade messenger bag bicycle rights pitchfork.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "Raw denim cardigan gastropub tousled fixie photo booth mustache.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Butcher single-origin coffee vhs vinyl cliche humblebrag drinking.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Helvetica narwhal 90's lo-fi.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "Tattooed cornhole authentic pinterest cleanse deep v drinking aesthetic meggings.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "Pitchfork asymmetrical selvage fingerstache goth direct trade sriracha synth.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "Cornhole small batch pug gastropub typewriter street.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "Etsy kale chips craft beer franzen thundercats godard organic whatever letterpress.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Sustainable try-hard you probably haven't heard of them distillery helvetica food truck slow-carb wolf.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Lomo stumptown cardigan iphone direct trade butcher offal pabst tofu.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Cronut hoodie tacos +1.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "Knausgaard everyday irony forage meggings.", author_id: 4, channel_id: 9, gif_url: nil},
  {body: "You probably haven't heard of them echo chicharrones pinterest biodiesel sriracha squid meh kombucha.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Dreamcatcher iphone sriracha +1.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Locavore ramps synth selvage.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Blog farm-to-table flexitarian synth craft beer pinterest wolf thundercats.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Mustache pbr&b cleanse health.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Five dollar toast tofu ramps tattooed humblebrag banh mi leggings cardigan pbr&b.", author_id: 52, channel_id: 9, gif_url: nil},
  {body: "Hi I'm Ryley, welcome to clack! :blush:", author_id: 51, channel_id: 1, gif_url: nil},
  {body: "Art party brunch five dollar toast keffiyeh meggings tacos pitchfork chicharrones 3 wolf moon.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Health sartorial stumptown pitchfork farm-to-table paleo messenger bag quinoa twee.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Craft beer pop-up wolf listicle echo.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Typewriter franzen yuccie kale chips loko viral single-origin coffee.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Twee pickled microdosing banh mi butcher street seitan salvia mumblecore.", author_id: 1, channel_id: 11, gif_url: nil},
  {body: "Locavore goth fixie selfies taxidermy.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Wayfarers iphone kogi cronut disrupt.", author_id: 1, channel_id: 11, gif_url: nil},
  {body: "Irony bicycle rights fingerstache marfa microdosing gluten-free cray stumptown.", author_id: 1, channel_id: 11, gif_url: nil},
  {body: "Art party shoreditch chicharrones messenger bag gastropub skateboard.", author_id: 1, channel_id: 11, gif_url: nil},
  {body: "Pour-over asymmetrical drinking wes anderson ugh iphone pork belly.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Swag skateboard pickled bicycle rights drinking.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Squid post-ironic asymmetrical truffaut offal selvage austin.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Sustainable actually bespoke waistcoat direct trade whatever locavore.", author_id: 1, channel_id: 11, gif_url: nil},
  {body: "Single-origin coffee whatever freegan chia cray williamsburg.", author_id: 1, channel_id: 11, gif_url: nil},
  {body: "Tote bag street aesthetic intelligentsia try-hard.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Godard ugh small batch vegan.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Whatever ramps banjo diy authentic carry.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Trust fund franzen cred literally iphone meditation swag mustache before they sold out.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Tilde normcore mlkshk lo-fi actually beard tattooed bushwick.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Small batch pickled heirloom fingerstache slow-carb carry.", author_id: 1, channel_id: 11, gif_url: nil},
  {body: "Farm-to-table leggings kogi cardigan tousled fixie knausgaard locavore.", author_id: 1, channel_id: 11, gif_url: nil},
  {body: "Craft beer pop-up hammock kombucha marfa waistcoat you probably haven't heard of them.", author_id: 1, channel_id: 11, gif_url: nil},
  {body: "Helvetica +1 readymade diy.", author_id: 1, channel_id: 11, gif_url: nil},
  {body: "Flannel mustache schlitz fingerstache occupy master green juice.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Stumptown readymade photo booth godard mixtape skateboard mumblecore fingerstache cred.", author_id: 53, channel_id: 11, gif_url: nil},
  {body: "Messenger bag chambray aesthetic tacos distillery ugh.", author_id: 2, channel_id: 12, gif_url: nil},
  {body: "Chia kombucha plaid godard lumbersexual dreamcatcher.", author_id: 2, channel_id: 12, gif_url: nil},
  {body: "You probably haven't heard of them shoreditch narwhal polaroid next level.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Cardigan authentic pickled brunch.", author_id: 2, channel_id: 12, gif_url: nil},
  {body: "Lomo mumblecore pork belly microdosing semiotics.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Deep v literally green juice cardigan mlkshk pbr&b blue bottle swag franzen.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Knausgaard fixie hoodie cold-pressed.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Hella franzen keytar typewriter ugh sartorial.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Lumbersexual brooklyn lo-fi synth.", author_id: 2, channel_id: 12, gif_url: nil},
  {body: "Mlkshk kinfolk shoreditch offal mumblecore banjo 8-bit tote bag distillery.", author_id: 2, channel_id: 12, gif_url: nil},
  {body: "Mixtape pug raw denim roof keffiyeh literally.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Brunch jean shorts fanny pack sustainable hashtag bitters pinterest.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Beard everyday wolf food truck tilde mustache stumptown.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Crucifix skateboard fingerstache next level street gastropub narwhal.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Vegan tacos bicycle rights 3 wolf moon cleanse.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Artisan lomo actually brunch kogi put a bird on it vhs paleo meh.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Marfa locavore sriracha lumbersexual.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Authentic freegan sartorial swag goth readymade.", author_id: 2, channel_id: 12, gif_url: nil},
  {body: "Ennui etsy selvage vinyl.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Drinking tumblr celiac whatever bitters plaid everyday banjo.", author_id: 2, channel_id: 12, gif_url: nil},
  {body: "Tacos mumblecore blue bottle goth lumbersexual.", author_id: 2, channel_id: 12, gif_url: nil},
  {body: "Mustache goth polaroid salvia.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Single-origin coffee art party bespoke jean shorts fixie pabst chillwave health.", author_id: 2, channel_id: 12, gif_url: nil},
  {body: "Diy cliche heirloom seitan master.", author_id: 53, channel_id: 12, gif_url: nil},
  {body: "Put a bird on it kogi messenger bag mixtape mustache.", author_id: 2, channel_id: 12, gif_url: nil},
  {body: "Cold-pressed ramps stumptown vice you probably haven't heard of them 3 wolf moon.", author_id: 53, channel_id: 13, gif_url: nil},
  {body: "Vhs umami truffaut fingerstache.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Echo poutine squid heirloom.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Goth next level swag chia wayfarers iphone schlitz.", author_id: 53, channel_id: 13, gif_url: nil},
  {body: "Selfies scenester austin echo narwhal salvia.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Migas kombucha selfies bespoke.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Tofu 90's typewriter migas blue bottle deep v microdosing.", author_id: 53, channel_id: 13, gif_url: nil},
  {body: "Kogi butcher sartorial tacos fanny pack gentrify health.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Tousled five dollar toast pbr&b literally ramps schlitz.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Xoxo migas neutra stumptown helvetica.", author_id: 53, channel_id: 13, gif_url: nil},
  {body: "Kickstarter pinterest tofu cardigan.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Squid yuccie cornhole park actually.", author_id: 53, channel_id: 13, gif_url: nil},
  {body: "Artisan asymmetrical master venmo butcher.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Wolf bushwick plaid forage godard vice stumptown waistcoat goth.", author_id: 53, channel_id: 13, gif_url: nil},
  {body: "Tofu distillery try-hard cold-pressed diy.", author_id: 53, channel_id: 13, gif_url: nil},
  {body: "Gastropub carry salvia thundercats cred you probably haven't heard of them pug migas.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Disrupt ethical chillwave fanny pack tousled tote bag quinoa hammock raw denim.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Flannel bushwick offal sustainable you probably haven't heard of them.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Schlitz next level kogi pork belly yolo.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Readymade authentic mlkshk ugh +1 hoodie trust fund vice.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Tacos celiac franzen vhs yr taxidermy pickled austin.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Fixie irony locavore knausgaard keffiyeh meh.", author_id: 53, channel_id: 13, gif_url: nil},
  {body: "Shoreditch kinfolk whatever everyday truffaut readymade chambray.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Distillery roof offal forage banjo aesthetic taxidermy pug.", author_id: 53, channel_id: 13, gif_url: nil},
  {body: "Wayfarers pbr&b aesthetic wolf cred 8-bit flexitarian.", author_id: 3, channel_id: 13, gif_url: nil},
  {body: "Chicharrones disrupt freegan lumbersexual church-key seitan yuccie photo booth.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Bicycle rights marfa roof tousled echo heirloom swag yr asymmetrical.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Cronut bespoke direct trade bushwick master skateboard lo-fi.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Fanny pack godard portland deep v neutra.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Thundercats mustache distillery put a bird on it cardigan viral before they sold out.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Kitsch tote bag poutine artisan hella vice.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Bushwick you probably haven't heard of them migas 3 wolf moon vhs post-ironic.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Chicharrones chambray blue bottle pour-over.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Pork belly chia loko try-hard food truck fashion axe squid.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Trust fund hoodie normcore park.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "8-bit selvage banh mi distillery occupy hoodie.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Keytar salvia normcore hoodie disrupt artisan.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Austin 8-bit plaid 3 wolf moon direct trade bitters cardigan.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Green juice schlitz loko tofu biodiesel banjo tumblr.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Loko intelligentsia plaid cardigan organic messenger bag five dollar toast selvage portland.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Meggings mustache lomo hammock yr.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Pickled listicle fashion axe locavore typewriter tacos.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Twee irony artisan gluten-free offal fixie put a bird on it beard shoreditch.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Food truck vegan blog pork belly waistcoat.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Retro church-key roof wes anderson tilde paleo lumbersexual.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Church-key salvia put a bird on it aesthetic meggings raw denim.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Ugh bushwick stumptown occupy selfies.", author_id: 4, channel_id: 14, gif_url: nil},
  {body: "Pug locavore thundercats tousled goth slow-carb williamsburg.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Mlkshk tattooed green juice flannel.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Wayfarers lumbersexual fingerstache venmo marfa artisan neutra kombucha.", author_id: 53, channel_id: 14, gif_url: nil},
  {body: "Hi I'm Ryley, welcome to clack! :blush:", author_id: 51, channel_id: 1, gif_url: nil},
  {body: "yo wassup", author_id: 53, channel_id: 1, gif_url: ""}
])
